baseURL = 'https://macchu.me/'
languageCode = 'en-us'
title = 'Macchu'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
site_logo = "Images/logo.png"
featured_image = '/images/gohugo-default-sample-hero-image.jpg'
background_color_class = "bg-black"
  subtitle = 'The Subtitle'
  